siteTitle = "OVERLAP"
siteDescription = "MA Computational Arts Show 2017"
siteKeywords = "Goldsmiths, MA Computational Arts, MACompArts, Overlap Show, creative computing"

noProductionJavascript = false
